### ISSUE TITLE
Add AirBnB config without the eslint-plugin-react dependency

### ISSUE THREAD

**Issue by jonnyarnold** [walmartlabs/eslint-config-defaults#40]
Hi there,

First, thanks for doing this - it's saved me a lot of time setting up a linter!

I'm doing an ES6 that doesn't have React (I know, weird). When I tried the naive config:

```json
{
 "extends": "defaults/configurations/airbnb",
 "rules": {
   "no-unused-vars": [1, {"vars": "all", "args": "after-used"}]
 }
}
```

then I get the following error:

```
ERROR in ./lib/reevoo-ping.js
Module build failed: Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint/lib/cli-engine.js:125:26
    at Array.forEach (native)
    at loadPlugins (/Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint/lib/cli-engine.js:116:21)
    at processText (/Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint/lib/cli-engine.js:204:5)
    at CLIEngine.executeOnText (/Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint/lib/cli-engine.js:686:26)
    at lint (/Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/jonny/reevoo/reevoo-ping-js/node_modules/eslint-loader/index.js:127:7)
```

I'm not using React, so this was a bit weird for me. I found that the AirBnB ruleset [has a set of React rules by default,](https://github.com/walmartlabs/eslint-config-defaults/blob/master/configurations/airbnb.js#L13) which seems to trigger the error.

To fix this for my project I just copied that ruleset, but without the React ruleset in it.

I'm wondering if:
- I'm the special one who wants the AirBnB configuration, but not the React stuff?
- Whether there's a need for a React-less AirBnB ruleset?

Thanks!

**Comment by baer** [comment]
Humm, I was wondering if this might happen to somebody. I listed the dependencies [here](https://github.com/walmartlabs/eslint-config-defaults#dependencies) but maybe you have an idea about how I could make that more obvious to folks.

With the airbnb config I literally copied their styles right into this project and if I pulled the React rules out I would be effectively deviating from their rules which is not something I want to get in the habit of doing. I  would also have to do a major rev since airbnb would need to go into a directory since I'd be maintaining 2 configs for them.

That said, their config SHOULD be generally useful with or without React so perhaps this is a good idea. If it's alright with you I am going to leave this issue open and revisit it after the ESLint 2.0 release is out. I thin I'm on board with splitting things out but I need to think on it.

**Comment by baer** [comment]
As a workaround you can pull this in as a proper dependency and use their config as is so long as the `eslint-plugin-react` is in your `package.json`. It would be an extraneous dependency but it won't hurt anything and your project should lint properly React or not.

**Comment by baer** [comment]
@jonnyarnold - Welp, it looks like the latest airbnb config does this already! I have a branch that will get you exactly what you need but it is based off of #42 so as soon as that is merged I'll PR it.

https://github.com/walmartlabs/eslint-config-defaults/tree/feature/update-airbnb-config

**Comment by baer** [comment]
Closed by https://github.com/walmartlabs/eslint-config-defaults/pull/47 - it will go out with the next release after the holidays.
